### ISSUE TITLE
Consider Properties

### ISSUE THREAD

**Issue by psykzz** [v1k45/python-qBittorrent#2]
I see a lot of get_global_download_limit and set_global_download_limit.

Have you considered just making those into properties instead?

``` python
api = Client()
api.login('a', 'b')
api.global_download_limit
>>> 5 # Or whatever.
```

**Comment by v1k45** [comment]
Yes, it will surely be a nice addition to the project. Will implement it in few days :)

**Comment by v1k45** [comment]
Hey @psykzz , I looked for available methods to convert them into properties and found few.

The problem here is that there are only few (4-5) methods which can be converted to properties and converting them will lead to inconsistencies. I am not sure if I should change them or not.

Please share your thoughts.

**Comment by psykzz** [comment]
Are you talking inconsistencies to how its implemented or how the user will use the class?
Ideally making things easier for the user is the ideal situation.

**Comment by v1k45** [comment]
I was talking about the user's side.
I kept the old `get/set_download/upload_limit` methods and added a separate property for them. This will keep things consistent.
Along with that, I am converting `api version info` methods to properties too. I'll push the updated code soon.

Other `get/set` methods require arguments, hence it is not appropriate to use them as properties.
Is there any other way convert arg taking methods to properties too?
