### ISSUE TITLE
STATUS_LIST in torrents is not correct

### ISSUE THREAD

**Issue by jerblack** [v1k45/python-qBittorrent#8]
According to this:
https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-Documentation#get-torrent-list

the status list should be:
'error', 'pausedUP', 'pausedDL', 'queuedUP', 'queuedDL', 'uploading', 'stalledUP', 'checkingUP',                       'checkingDL', 'downloading', 'stalledDL'

**Comment by v1k45** [comment]
The torrent state and torrent list filters are different things here.

The `STATUS_LIST` is a list of possible values of torrent listing filters. Whereas, the torrent state is the current value of the individual torrent.
The documentation clearly mentions the possible filters. I used `STATUS` instead of `FILTER` just for the sake of readability.

Correct me if I am wrong.

**Comment by v1k45** [comment]
One month is more than enough time to wait for response. Closing the issue. Feel free to re-open :)
